# Starter pipeline
# Mininal project with default and build stages.
#

# **********************************************************
# Define a pipeline name
# **********************************************************

name: $[variables['branchName']]

# **********************************************************
# Define the global agent pull default
# **********************************************************

pool:
  vmImage: 'Ubuntu-20.04'

# **********************************************************
# Define global variables
# **********************************************************

variables:
- template: templates/vars.yml
- group: environment-develop
- group: environment-stage
- group: environment-production

# **********************************************************
# Triggers rules only in branches
# **********************************************************

trigger:
  branches:
    include: ['main', 'stage', 'develop']
  paths:
    include: ['*']
    exclude: ['docs/*']

# **********************************************************
# Pull Request
# **********************************************************

pr: none

# **********************************************************
# Define pipeline stages
# **********************************************************

stages:
- template: templates/build.yml
  parameters:
    dockerServiceConnection: 'YOUR-INFORMATION'
- template: templates/deploy.yml
