# ==============================================================================
# STEPS
# ==============================================================================

steps:
- download: none

- script: echo Deploy to Azure App Service!
