name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0

      - name: Secret Detection
        uses: zricethezav/gitleaks-action@d3511a7d371653093f9527416819704784817957
        with:
          config-path: ${{ github.workspace }}/.github/config/.gitleaks.toml
        continue-on-error: false
