name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Secret Detection
        uses: zricethezav/gitleaks-action@fb6e139b0e53e60e80dd1717b0462de3dbb475d3
        with:
          config-path: ${{ github.workspace }}/.github/config/.gitleaks.toml
        continue-on-error: false
